<?php

/**
 * ArticleTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object ArticleTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Article');
	}

	public function getListOnPage($page=1,$limit=18){
		$page = $page<=0?1:$page;
		return $this->createQuery()->offset(($page-1)*$limit)->limit($limit);
	}
	
	public function getIndexArticle($cagegory_id = 1,$notin = array(),$limit=15) {
		$query = Doctrine_Core::getTable('Article')->createQuery('a');
		$query->select('a.id,a.title')->where('a.category_id=?', $cagegory_id)
		->andWhereNotIn('a.id', $notin)
		->andWhere('a.is_approved=1')
		->andWhere('a.is_rejected=0')
		->orderBy('a.id DESC')->limit($limit);
		return $query->execute();
	}
	
	public function getArticleForRecommend($type) {
		if($type == '佛教资讯A1' || $type == '佛教资讯A2') {
			$category = 1;
		} else if($type == '慈善救助A3' || $type == '慈善救助A4'){
			$category = 3;
		} else  if($type == '追忆祭文A5' || $type == '追忆祭文A6') {
			$category = 5;
		} else if($type == '同城活动A7' || $type == '同城活动A8') {
			$category = 4;
		}
		
		$query = $this->createQuery();
		$query->select('id,title')->where('is_approved=1 AND is_rejected=0')
			  ->andWhere('category_id=?', $category);
			  
		return $query->execute();
	}
	
}