<?php

/**
 * Article
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfonymodel
 * @subpackage model
 * @author     Mia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article extends BaseArticle
{
	static public function getFileDir()
	{
		return sfConfig::get('sf_upload_dir') . '/article';
	}

	public function getPublicFileLocation1()
	{
		return str_replace(sfConfig::get('sf_web_dir'), '', self::getFileDir()) . '/' . $this->getImgOne();
	}

	public function getPublicFileLocation2()
	{
		return str_replace(sfConfig::get('sf_web_dir'), '', self::getFileDir()) . '/' . $this->getImgTwo();
	}

	public function getPublicFileLocation3()
	{
		return str_replace(sfConfig::get('sf_web_dir'), '', self::getFileDir()) . '/' . $this->getImgThree();
	}

	public function save( Doctrine_Connection $conn = null ) {
		$user_id = sfContext::getInstance()->getUser()->getGuardUser()->getId();
		$this->setUserId($user_id);

		return parent::save( $conn );

	}

	public function delete(Doctrine_Connection $conn = null) {
		if($this->getImgOne() != '')
			unlink(sfConfig::get('sf_upload_dir').'/article/'.$this->getImgOne());

		if($this->getImgTwo() != '')
			unlink(sfConfig::get('sf_upload_dir').'/article/'.$this->getImgTwo());
			
		if($this->getImgThree() != '')
			unlink(sfConfig::get('sf_upload_dir').'/article/'.$this->getImgThree());

		return parent::delete($conn);
	}
}