<?php

/**
 * BuddhaHistoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BuddhaHistoryTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object BuddhaHistoryTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('BuddhaHistory');
	}
	
	public function getListOnPage($page=1,$limit=18){
		$page = $page<=0?1:$page;
		return $this->createQuery()->offset(($page-1)*$limit)->limit($limit);
	}
}