<?php

/**
 * BunddlaHall
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    pszx
 * @subpackage model
 * @author     MIA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BunddlaHall extends BaseBunddlaHall
{
	static public function getFileDir()
	{
		return sfConfig::get('sf_upload_dir') . '/buddha';
	}

	public function getPublicFileLocation()
	{
		return str_replace(sfConfig::get('sf_web_dir'), '', self::getFileDir()) . '/' . $this->getImages();
	}

	public function save( Doctrine_Connection $conn = null ) {
		$user_id = sfContext::getInstance()->getUser()->getGuardUser()->getId();
		$this->setUserId($user_id);

		return parent::save( $conn );

	}

	public function delete(Doctrine_Connection $conn = null) {
		if($this->getImages() != '')
			unlink(sfConfig::get('sf_upload_dir').'/buddha/'.$this->getImages());
			
		return parent::delete($conn);
	}
}