<?php

/**
 * FileUploadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileUploadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FileUploadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FileUpload');
    }
}