<?php

/**
 * MemorialCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemorialCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MemorialCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MemorialCategory');
    }
}