<?php

/**
 * MemorialTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemorialTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object MemorialTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Memorial');
	}
	public function getListOnPage($page=1,$limit=18){
		$page = $page<=0?1:$page;
		return $this->createQuery('m')->offset(($page-1)*$limit)->limit($limit);
	}
}