<?php

/**
 * OblationCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OblationCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OblationCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OblationCategory');
    }
}