<?php

/**
 * OtwrHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OtwrHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OtwrHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OtwrHistory');
    }
}