<?php

/**
 * PrayWordsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrayWordsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrayWordsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PrayWords');
    }
}