<?php

/**
 * RecommendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecommendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecommendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Recommend');
    }
}