<?php

/**
 * Temple
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfonymodel
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Temple extends BaseTemple
{
	static public function getFileDir()
	{
		return sfConfig::get('sf_upload_dir') . '/temple';
	}

	public function getPublicFileLocation1()
	{
		return str_replace(sfConfig::get('sf_web_dir'), '', self::getFileDir()) . '/' . $this->getImgOne();
	}

	public function getPublicFileLocation2()
	{
		return str_replace(sfConfig::get('sf_web_dir'), '', self::getFileDir()) . '/' . $this->getImgTwo();
	}

	public function getPublicFileLocation3()
	{
		return str_replace(sfConfig::get('sf_web_dir'), '', self::getFileDir()) . '/' . $this->getImgThree();
	}

	public function save( Doctrine_Connection $conn = null ) {
		$user = sfContext::getInstance()->getUser()->getGuardUser();

		if($user) {
			$this->setLastModify($user->getUsername());
		} else {
			$this->setLastModify(' ');
		}

		return parent::save( $conn );

		return parent::save( $conn );

	}

	public function delete(Doctrine_Connection $conn = null) {
		if($this->getImgOne() != '')
		unlink(sfConfig::get('sf_upload_dir').'/temple/'.$this->getImgOne());

		if($this->getImgTwo() != '')
		unlink(sfConfig::get('sf_upload_dir').'/temple/'.$this->getImgTwo());
			
		if($this->getImgTwo() != '')
		unlink(sfConfig::get('sf_upload_dir').'/temple/'.$this->getImgTwo());

		return parent::delete($conn);
	}
}