<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfonymodel
 * @subpackage model
 * @author     Mia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
	public function getHigerPermission() {
		
		if($this->hasPermission('high')) {
			return '高级管理员';
		}
		
		if($this->hasPermission('senior')) {
			return '中级管理员';
		}
		
		if($this->hasPermission('primary')) {
			return '初级管理员';
		}
	}
}