<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    symfonymodel
 * @subpackage model
 * @author     Mia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
	public function getHigerPermission() {
		
		if($this->hasPermission('high')) {
			return 'high';
		}
		
		if($this->hasPermission('senior')) {
			return 'senior';
		}
		
		if($this->hasPermission('primary')) {
			return 'primary';
		}
	}
}